apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp3 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapp3
  template:
    metadata:
      labels:
        app: samplewebapp3 
    spec:
      containers:
        - name: samplewebapp3 
          image: clusterregister1976.azurecr.io/samplewebapp3
          ports:
          - containerPort: 80
